### PR TITLE
feat: support multicall in godwoken v1

### PR DESCRIPTION
**Pull request by homura**
- a script for deploying multicall2 to Godwoken
- get ERC20 balance via multicall2 on Godwoken v1

### CODE REVIEW

**Review by zhangyouxin — APPROVED** [review]
LGTM

**Comment by Kuzirashi** [comment]
We also have Multicall3 deployed to a deterministic address on testnet: https://github.com/mds1/multicall

:)

cc @homura @zhangyouxin

**Comment by homura** [comment]
hi, @Kuzirashi do we have plans to deploy `multicall3` on Godwoken mainnet?

**Comment by Kuzirashi** [comment]
@homura Sure, why not. I will start working on it as soon as we have Godwoken Bridge for mainnet ready (when light-godwoken adds support for mainnet).

**Pull request merged**
